# Generated by Django 4.1.7 on 2023-10-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='profilepic',
        ),
    ]
