# Generated by Django 4.1.7 on 2023-10-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0004_rename_image_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.FileField(upload_to='images'),
        ),
    ]
