# Generated by Django 4.1.7 on 2023-10-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0007_remove_profile_profilepic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
