# Generated by Django 4.1.7 on 2023-10-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='media',
        ),
    ]
