# Generated by Django 4.1.7 on 2023-10-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0011_alter_post_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
    ]
