# Generated by Django 4.1.7 on 2023-10-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0012_remove_post_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='user_id',
            new_name='user',
        ),
    ]
