# Generated by Django 4.1.7 on 2023-10-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0013_rename_post_id_likepost_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='like_post',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
