# Generated by Django 4.1.7 on 2023-10-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0014_likepost_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='like_post',
            new_name='like_count',
        ),
    ]
