# Generated by Django 4.1.7 on 2023-10-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0015_rename_like_post_likepost_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='like_count',
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
