# Generated by Django 4.1.7 on 2023-10-25 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0016_remove_likepost_like_count_post_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='likes_count',
        ),
    ]
