# Generated by Django 4.1.7 on 2023-10-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0019_remove_post_likes_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_id',
        ),
    ]
