# Generated by Django 4.1.7 on 2023-10-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0020_rename_post_comment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
