# Generated by Django 4.1.7 on 2023-10-27 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0022_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='social_media_app.userprofile'),
        ),
    ]
