# Generated by Django 4.1.7 on 2023-10-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0023_post_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user2',
        ),
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
