# Generated by Django 4.1.7 on 2023-10-28 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0024_remove_post_user2_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='social_media_app.userprofile'),
            preserve_default=False,
        ),
    ]
