# Generated by Django 4.1.7 on 2023-10-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0028_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discription',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='social_media_app.userprofile'),
        ),
    ]
