# Generated by Django 4.1.7 on 2023-11-03 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0031_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='social_media_app.userprofile'),
        ),
    ]
