# Generated by Django 4.1.7 on 2023-11-04 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0034_notification_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
