# Generated by Django 4.1.7 on 2023-11-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0035_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(default='requested', max_length=10),
        ),
    ]
