# Generated by Django 4.1.7 on 2023-11-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0038_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
